#%RAML 1.0 NamedExample

value:
  - id: "A0001"
    firstName: "Fabricio"
    lastName: "Catae"
    address: "Av Roberto Marinho"
    postal: "12345-000"
    country: "Brazil"
    miles: 10
    creationDate: 2019-06-01T09:00:00.000Z
    type: "personal"

  - id: "A0002"
    firstName: "Fernando"
    lastName: "Catae"
    address: "Av Paulista"
    postal: "11111-000"
    country: "Brazil"
    miles: 5
    creationDate: 2019-06-01T09:00:00.000Z
    type: "business"
