#%RAML 1.0
version: v1
title: Lab Accounts API

types:
  Account: !include types/account.raml

traits:
  requester:
    headers:
      Requester-ID: string

/accounts:
  description: Usuarios cadastrados no sistema centralizado
  is: [requester]  
  get:
    description: Retorna a lista de pessoas registradas no sistema
    queryParameters:
      type:
        required: true
        enum: [personal, business]        
      name?: string
      country?: string
    responses:
      200:
        body:          
          application/json:
            type: Account[]
            example: !include examples/account-list.raml
      400:
        description: Not found
        body:
          application/json:
            example: {
              "message": "No results"
            }
            
  post:
    description: Inclui uma lista de pessoas
    body:
      application/json:
        type: Account[]      
    responses:
      201:
        body:
          application/json:
            example: {
              "message": "Account created (but not really)"
            }
      400:
        body:
          application/json:
            example: {
              "message": "No rows to insert"
            }