@baseurl = ...

###
GET {{baseurl}}/accounts?type=personal
Requester-ID: client01

###
POST {{baseurl}}/accounts
Content-Type: application/json
Requester-ID: client01

[
  {
    "id": "A0001",
    "firstName": "Fabricio",
    "lastName": "Catae",
    "address": "Av Roberto Marinho",
    "postal": "12345-000",
    "country": "Brazil",
    "miles": 10,
    "creationDate": "2019-06-01T09:00:00.000Z",
    "type": "personal"
  }
]