GET http://localhost:8081/foo

###
POST http://localhost:8081/food
Content-Type: application/json

{
    "card_no": "T2",
    "amount_granted": 2.3
}

###
POST http://localhost:8081/meals
Content-type: application/json

{
	"card_no": "v6",
	"amount_granted": 111
}

###
POST http://localhost:8081/online
Content-type: application/json

{
	"card_no": "o1",
	"amount_granted": 100000
}