#%RAML 1.0 DataType

properties:
  id?: string
  firstName: string
  lastName: string
  address: string
  postal: string
  country: string
  miles: integer
  creationDate?: datetime
  type: string

example:
  id: "A0001"
  firstName: "Fabricio"
  lastName: "Catae"
  address: "Av Roberto Marinho"
  postal: "12345-000"
  country: "Brazil"
  miles: 10
  creationDate: 2019-06-01T09:00:00.000Z
  type: "personal"